apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet 
metadata:
  name: core-deploy-hostnetwork
  namespace: sset-5g-simulation
  labels:
    ngc-mode: core
spec:
  replicas: 1
  serviceName: "core-node-host-pool"
  selector:
    matchLabels:
      ngc-mode: core
  template:
    metadata:          
      labels:
        ngc-mode: core
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      #terminationGracePeriodSeconds: 60
      containers:
        - name: sset-cn
          image: sset-5g-uerancn:v1.0
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Always
          env:
            - name: IPV4_TUN_ADDR
              value: "100.46.0.1/16"
            - name: IPV6_TUN_ADDR
              value: "cafe::1/64"
            - name: DB_URI
              value: mongodb://mongo-node-pool/open5gs
          command: ["/bin/sh", "-c"]
          args:
            - echo "CN starting";
              cp /usr/local/install/SSET/cnf/5G/core/sample-tmp.yaml /usr/local/install/SSET/cnf/5G/core/sample.yaml;
              sed -i 's|IPV4_TUN_ADDR|'$IPV4_TUN_ADDR'|g' /usr/local/install/SSET/cnf/5G/core/sample.yaml;
              /bin/bash sset_5g_network.sh ${IPV4_TUN_ADDR} ${IPV6_TUN_ADDR};
              /bin/bash sset_5g_core_tools.sh 5gcK8s
          ports:
            - name: ngap 
              containerPort: 38412
              protocol: SCTP
            - name: gtp-u
              containerPort: 2152
              protocol: UDP            
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: sample-config
              mountPath: /usr/local/install/SSET/cnf/5G/core/sample-tmp.yaml
              subPath: "sample-tmp.yaml"  
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: sample-config
          configMap:
            name: core-config    
            items:
            - key: sample.yaml
              path: sample-tmp.yaml