apiVersion: v1
kind: Service
metadata:
  name: mongo-node-pool
  namespace: sset-5g-simulation
  labels:
    ngc-mode: mongo
spec:
  type: NodePort
  ports:
  - name: webui-com 
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30000
  publishNotReadyAddresses: true
  selector:
    ngc-mode: mongo
