apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-pool
  namespace: sset-5g-simulation
  labels:
    ngc-mode: mongo
spec:
  type: ClusterIP
  ports:
  - name: mongo-com 
    port: 27017
    targetPort: 27017
  publishNotReadyAddresses: true
  selector:
    ngc-mode: mongo
