version: '3'

services:
  cnrun:
    network_mode: "host"
    image: oset-env-base:ubuntu20.04
    container_name: sset-cn-host
    env_file:
      - nacos.env
    volumes:
      - ./step02-sset/in:/home/cn
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
      - "2152/udp"
      - "38412/sctp"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    #docker V18.09 open
    #sysctls:
    #  - net.ipv4.ip_forward=1
    #  - net.ipv6.conf.all.disable_ipv6=0
    command: /bin/bash -c "dpkg -i /home/cn/sset_install/oset/*.deb; dpkg -i /home/cn/sset_install/sset/5gcn/nacos/*.deb; /bin/bash /home/cn/sset_5g_network.sh ${UPF_SUB4_IP} ${UPF_SUB6_IP}; /bin/bash /home/cn/sset_5g_core_tools.sh 5gcDocker -n ${NACOS_IP}"