version: '3'

services:
  cnrun:
    image: sset-cn-base:v1.0.1-1
    container_name: sset-cn-bridge-${CN_IP}
    env_file:
      - nacos.env
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
      - "2152/udp"
      - "38412/sctp"
    # ports:
    #   - "2152:2152/udp"
    #   - "38412:38412/sctp"
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    #  - net.ipv6.conf.all.disable_ipv6=0
    #devices:
    #  - "/dev/net/tun:/dev/net/tun"
    command: /bin/bash -c "/bin/bash sset_5g_network.sh ${UPF_SUB4_IP} ${UPF_SUB6_IP}; /bin/bash  sset_5g_core_tools.sh 5gcDocker -n ${NACOS_IP}"
    networks:
      default:
        ipv4_address: ${CN_IP}

networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}