apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet 
metadata:
  name: uerancn-deploy
  namespace: sset-5g-simulation
  labels:
    ngc-mode: uerancn
spec:
  replicas: 1
  #serviceName: "uerancn-svc-pool"
  serviceName: "uerancn-node-pool"
  selector:
    matchLabels:
      ngc-mode: uerancn
  template:
    metadata:          
      labels:
        ngc-mode: uerancn
    spec:
      serviceAccountName: mongo
      automountServiceAccountToken: true
      #terminationGracePeriodSeconds: 60
      containers:
        - name: mongo
          image: oset-mongo-simple:v1.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - '/bin/bash mongo_init.sh'
          ports:
            - name: mongo-com 
              containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /var/lib/mongodb
        - name: webui
          image: oset-webui-simple:v1.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - '/bin/bash webui_init.sh'
          ports:
            - name: webui-com 
              containerPort: 3000
          env:
            - name: DB_URI
              value: mongodb://localhost/open5gs
        - name: sset-cn
          image: sset-5g-uerancn:v1.0
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Always
          env:
            - name: IPV4_TUN_ADDR
              value: "100.45.0.1/16"
            - name: IPV6_TUN_ADDR
              value: "cafe::1/64"
            - name: DB_URI
              value: mongodb://localhost/open5gs
          command: ["/bin/sh", "-c"]
          args:
            - echo "CN starting";
              sleep 5;
              /bin/bash sset_5g_network.sh ${IPV4_TUN_ADDR} ${IPV6_TUN_ADDR};
              /bin/bash sset_5g_core_tools.sh 5gcK8s
          ports:
            - name: ngap 
              containerPort: 38412
              protocol: SCTP
            - name: gtp-u
              containerPort: 2152
              protocol: UDP            
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: sample-config
              mountPath: /usr/local/install/SSET/cnf/5G/core/sample.yaml
              subPath: "sample.yaml" 
        - name: sset-gnb
          image: sset-5g-uerancn:v1.0
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - echo "GNB starting";
              /bin/bash sset_5g_ueran_tools.sh gnb -Y          
          volumeMounts:
            - name: gnb-config
              mountPath: /usr/local/install/SSET/cnf/5G/ueran/sset5g-gnb.yaml
              subPath: "sset5g-gnb.yaml"
        - name: sset-ue
          image: sset-5g-uerancn:v1.0
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args:
            - echo "UE starting";
              /bin/bash sset_5g_ueran_tools.sh ue -Y    
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: ue-config
              mountPath: /usr/local/install/SSET/cnf/5G/ueran/sset5g-ue.yaml
              subPath: "sset5g-ue.yaml"             
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: sample-config
          configMap:
            name: uerancn-config    
            items:
            - key: sample.yaml
              path: sample.yaml
        - name: gnb-config
          configMap:
            name: uerancn-config    
            items:
            - key: gnb.yaml
              path: sset5g-gnb.yaml
        - name: ue-config
          configMap:
            name: uerancn-config    
            items:
            - key: ue.yaml
              path: sset5g-ue.yaml
        - name: mongo-persistent-storage
          emptyDir: {}
            #medium: Memory
            #sizeLimit: 100Mi
      #volumeClaimTemplates:
        #- metadata:
            #name: mongo-persistent-storage
          #spec:
            #accessModes: [ "ReadWriteOnce" ]
            #resources:
               #requests:
               #storage: 2Gi