apiVersion: v1
kind: ConfigMap
metadata:
  name: uerancn-config
  namespace: sset-5g-simulation
  labels:
    ngc-mode: uerancn
data:
######################################
  sample.yaml: |
    logger:
      level: info

    nrf:
        sbi:
          - addr: 127.0.0.10
            port: 7777

    smf:
        sbi:
          - addr: 127.0.0.4
            port: 7777
        gtpc:
          - addr: 127.0.0.4
        gtpu:
          - addr: 127.0.0.4
        pfcp:
          - addr: 127.0.0.4
        subnet:
          - addr: 100.45.0.1/16
            #dnn: cmnet
        dns:
          - 8.8.8.8
          - 8.8.4.4
          - 2001:4860:4860::8888
          - 2001:4860:4860::8844
        mtu: 1400
        freeDiameter: /usr/local/install/SSET/cnf/5G/core/freeDiameter/smf.conf

    amf:
      sbi:
        - addr: 127.0.0.5
          port: 7777
      ngap:
        #- dev: eth0
        #- addr: cn-svc-pool
        - addr: 127.0.0.5
      guami:
        - plmn_id:
            mcc: 901
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 901
            mnc: 70
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 901
            mnc: 70
          s_nssai:
           - sst: 1
      security:
          integrity_order : [ NIA2, NIA1, NIA0 ]
          ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
          full: Open5GS
      amf_name: open5gs-amf0

    upf:
        pfcp:
          - addr: 127.0.0.7
        gtpu:
          #- dev: eth0
          #- addr: cn-svc-pool
          - addr: 127.0.0.7
        subnet:
          - addr: 100.45.0.1/16
            #dnn: cmnet    
            #dev: ogstun

    ausf:
      sbi:
        - addr: 127.0.0.11
          port: 7777

    udm:
      sbi:
        - addr: 127.0.0.12
          port: 7777

    pcf:
      sbi:
        - addr: 127.0.0.13
          port: 7777

    nssf:
      sbi:
        - addr: 127.0.0.14
          port: 7777
      nsi:
        - addr: 127.0.0.10
          port: 7777
          s_nssai:
            sst: 1

    bsf:
      sbi:
        - addr: 127.0.0.15
          port: 7777

    udr:
      sbi:
        - addr: 127.0.0.20
          port: 7777

  gnb.yaml: |
    mcc: '901'
    mnc: '70'

    nci: '0x0000000100'
    idLength: 32
    tac: 1

    linkIp: 127.0.0.100
    ngapIp: 127.0.0.100
    gtpIp: 127.0.0.100

    amfConfigs:
      - address: 127.0.0.5
        port: 38412

    slices:
      - sst: 1

    ignoreStreamIds: true
    # SSET config
    mainctrl:
      - address: 10.37.5.69
        port: 1001

    nacos:
      - address: 10.37.5.69
        cluster: 10-37-6-29

    rocketmq:
      - address: 10.37.5.69
        port: 9876

  ue-1.yaml: |
    supi: 'imsi-901700000000001'
    mcc: '901'
    mnc: '70'

    key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
    op: 'E8ED289DEBA952E4283B54E88E6183CA'
    opType: 'OPC'
    amf: '8000'
    imei: '356938035643803'
    imeiSv: '4370816125816151'

    gnbSearchList:
      - 127.0.0.100

    uacAic:
      mps: false
      mcs: false

    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
  
    sessions:
      - type: 'IPv4'
        apn: internet
        slice:
          sst: 1

    configured-nssai:
      - sst: 1

    default-nssai:
      - sst: 1
        sd: 1

    integrity:
      IA1: true
      IA2: true
      IA3: true

    ciphering:
      EA1: true
      EA2: true
      EA3: true

    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'

    # SSET config
    mainctrl:
      - address: 10.37.5.69
        port: 1001

    nacos:
      - address: 10.37.5.69
        cluster: 10-37-6-29

    rocketmq:
      - address: 10.37.5.69
        port: 9876