apiVersion: v1
kind: Service
metadata:
  name: gnb-svc-pool
  namespace: sset-5g-simulation
  labels:
    ngc-mode: gnb
spec:
  type: ClusterIP
  clusterIP: None
  #ports:
  #- name: ngap 
  #  port: 38412
  #  targetPort: 38412
  #  protocol: SCTP
  #- name: gtp-u
  #  port: 2152
  #  targetPort: 2152
  #  protocol: UDP
  #publishNotReadyAddresses: true
  selector:
    ngc-mode: gnb
