apiVersion: v1
kind: ConfigMap
metadata:
  name: cn-config
  namespace: sset-5g-simulation
  labels:
    ngc-mode: cn
data:
######################################
  nrf.yaml: |
    logger:
      level: info
      #file: /usr/local/install/SSET/var/log/core/nrf.log

    #db_uri: mongodb://localhost/open5gs

    nrf:
        sbi:
          - addr: 127.0.0.10
            port: 7777
######################################      
  smf.yaml: |
    logger:
      level: info

    smf:
        sbi:
          - addr: 127.0.0.4
            port: 7777
        gtpc:
          - addr: 127.0.0.4
        gtpu:
          - addr: 127.0.0.4
        pfcp:
          - addr: 127.0.0.4
        subnet:
          - addr: 100.45.0.1/16
            #dnn: cmnet
        dns:
          - 8.8.8.8
          - 8.8.4.4
          - 2001:4860:4860::8888
          - 2001:4860:4860::8844
        mtu: 1400
        freeDiameter: /usr/local/install/SSET/cnf/5G/core/freeDiameter/smf.conf

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777

    upf:
      pfcp:
        - addr: 127.0.0.7
      gtpu:
        - addr: 127.0.0.7
      subnet:
        - addr: 100.45.0.1/16
######################################
  amf.yaml: |
    logger:
      level: info

    amf:
      sbi:
        - addr: 127.0.0.5
          port: 7777
      ngap:
        - dev: eth0
        #- addr: cn-svc-pool
      guami:
        - plmn_id:
            mcc: 901
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 901
            mnc: 70
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 901
            mnc: 70
          s_nssai:
           - sst: 1
      security:
          integrity_order : [ NIA2, NIA1, NIA0 ]
          ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
          full: Open5GS
      amf_name: open5gs-amf0

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777
######################################
  ausf.yaml: |
    logger:
      level: info

    ausf:
      sbi:
        - addr: 127.0.0.11
          port: 7777

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777
######################################
  udm.yaml: |
    logger:
      level: info

    udm:
      sbi:
        - addr: 127.0.0.12
          port: 7777

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777
######################################
  pcf.yaml: |
    logger:
      level: info

    #db_uri: mongodb://localhost/open5gs

    pcf:
      sbi:
        - addr: 127.0.0.13
          port: 7777

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777
######################################
  nssf.yaml: |
    logger:
      level: info

    nssf:
      sbi:
        - addr: 127.0.0.14
          port: 7777
      nsi:
        - addr: 127.0.0.10
          port: 7777
          s_nssai:
            sst: 1

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777
######################################
  bsf.yaml: |
    logger:
      level: info

    #db_uri: mongodb://localhost/open5gs

    bsf:
      sbi:
        - addr: 127.0.0.15
          port: 7777

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777
######################################
  udr.yaml: |
    logger:
      level: info

    #db_uri: mongodb://localhost/open5gs

    udr:
      sbi:
        - addr: 127.0.0.20
          port: 7777

    nrf:
      sbi:
        - addr: 127.0.0.10
          port: 7777
######################################
  upf.yaml: |
    logger:
      level: info

    upf:
        pfcp:
          - addr: 127.0.0.7
        gtpu:
          - dev: eth0
          #- addr: cn-svc-pool
        subnet:
          - addr: 100.45.0.1/16
            #dnn: cmnet    
            #dev: ogstun
######################################
#  entrypoint.sh: |
#    #!/bin/bash
#    `````
#    exit 1
