apiVersion: v1
kind: Service
metadata:
  name: cn-svc-pool
  namespace: sset-5g-simulation
  labels:
    ngc-mode: cn
spec:
  type: ClusterIP
  #clusterIP: None #10.233.3.127
  ports:
  - name: ngap 
    port: 38412
    targetPort: 38412
    protocol: SCTP
  - name: gtp-u
    port: 2152
    targetPort: 2152
    protocol: UDP
  #- name: mongo-com 
  #  port: 27017
  #  targetPort: 27017
  #- name: webui-com 
  #  port: 3000
  #  targetPort: 3000
  #  protocol: TCP
  publishNotReadyAddresses: true
  selector:
    ngc-mode: cn
