apiVersion: v1
kind: Service
metadata:
  name: cn-node-pool
  namespace: sset-5g-simulation
  labels:
    ngc-mode: cn
spec:
  type: NodePort
  ports:
  #- name: ngap 
  #  port: 38412
  #  targetPort: 38412
  #  protocol: SCTP
  #  nodePort: 38412
  #- name: gtp-u
  #  port: 2152
  #  targetPort: 2152
  #  protocol: UDP
  #  nodePort: 2152
  #- name: mongo-com 
  #  port: 27017
  #  targetPort: 27017
  #  nodePort: 27017
  - name: webui-com 
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30000
  publishNotReadyAddresses: true
  selector:
    ngc-mode: cn
