apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-config
  namespace: sset-5g-simulation
  labels:
    ngc-mode: ue
data:
######################################
  ue.yaml: |
    supi: INITAL_SUPI
    mcc: '901'
    mnc: '70'

    key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
    op: 'E8ED289DEBA952E4283B54E88E6183CA'
    opType: 'OPC'
    amf: '8000'
    imei: '356938035643803'
    imeiSv: '4370816125816151'

    gnbSearchList:
      - gnb-svc-pool

    uacAic:
      mps: false
      mcs: false

    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
  
    sessions:
      - type: 'IPv4'
        apn: internet
        slice:
          sst: 1

    configured-nssai:
      - sst: 1

    default-nssai:
      - sst: 1
        sd: 1

    integrity:
      IA1: true
      IA2: true
      IA3: true

    ciphering:
      EA1: true
      EA2: true
      EA3: true

    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'

    # SSET config
    mainctrl:
      - address: 10.37.5.69
        port: 1001

    nacos:
      - address: 10.37.5.69
        cluster: 10-37-6-29

    rocketmq:
      - address: 10.37.5.69
        port: 9876