apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  namespace: sset-5g-simulation
  labels:
    ngc-mode: core
data:
######################################
  sample.yaml: |
    logger:
      level: info

    nrf:
        sbi:
          - addr: 127.0.0.10
            port: 7777

    smf:
        sbi:
          - addr: 127.0.0.4
            port: 7777
        gtpc:
          - addr: 127.0.0.4
        gtpu:
          - addr: 127.0.0.4
        pfcp:
          - addr: 127.0.0.4
        subnet:
          - addr: IPV4_TUN_ADDR
            #dnn: cmnet
        dns:
          - 8.8.8.8
          - 8.8.4.4
          - 2001:4860:4860::8888
          - 2001:4860:4860::8844
        mtu: 1400
        freeDiameter: /usr/local/install/SSET/cnf/5G/core/freeDiameter/smf.conf

    amf:
      sbi:
        - addr: 127.0.0.5
          port: 7777
      ngap:
        - dev: eth0
        #- addr: cn-svc-pool
        #- addr: 127.0.0.5
      guami:
        - plmn_id:
            mcc: 901
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 901
            mnc: 70
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 901
            mnc: 70
          s_nssai:
           - sst: 1
      security:
          integrity_order : [ NIA2, NIA1, NIA0 ]
          ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
          full: Open5GS
      amf_name: open5gs-amf0

    upf:
        pfcp:
          - addr: 127.0.0.7
        gtpu:
          - dev: eth0
          #- addr: cn-svc-pool
          #- addr: 127.0.0.7
        subnet:
          - addr: IPV4_TUN_ADDR
            #dnn: cmnet    
            #dev: ogstun

    ausf:
      sbi:
        - addr: 127.0.0.11
          port: 7777

    udm:
      sbi:
        - addr: 127.0.0.12
          port: 7777

    pcf:
      sbi:
        - addr: 127.0.0.13
          port: 7777

    nssf:
      sbi:
        - addr: 127.0.0.14
          port: 7777
      nsi:
        - addr: 127.0.0.10
          port: 7777
          s_nssai:
            sst: 1

    bsf:
      sbi:
        - addr: 127.0.0.15
          port: 7777

    udr:
      sbi:
        - addr: 127.0.0.20
          port: 7777